//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFIZER_FFVV.Presentacion.Vista.Simulador
{


    public partial class SimuladorTerritorios
    {
    }
}
